services:
  todohateoas:
    image: todohateoas
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3307/todo
      - SPRING_DATASOURCE_USERNAME=erick
      - SPRING_DATASOURCE_PASSWORD=erick
    depends_on:
      - database

  database:
    image: mysql:latest 
    container_name: mysql_database  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: erick
      MYSQL_DATABASE: todo
      MYSQL_USER: erick
      MYSQL_PASSWORD: erick
    ports:
      - 3307:3307  
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
